### ISSUE TITLE
TODO list wake tracking

### ISSUE THREAD

**Issue by lgiacome** [xsuite/xwakes#13]
- [ ] parametrize single slice displacement tests to work directly on resonator or on a table built from a resonator
- [ ] length in thick wall components
- [ ] docstrings and add to reference guid
- [ ] test with yokoya factors
- [ ] improve multiturn tests (include check on reset after `num_turns`)
- [ ] autoconfig for coupled bunch
- [ ] specific test on concolution module
- [ ] clean examples
- [ ] monitor
- [ ] test for HT table read
- [ ] tests with wake in front (i.e. non-ultrarelativistic bunch)
- [ ] test with instability
- [ ] MPI

**Comment by lgiacome** [comment]
Can we test with mpi?

**Comment by lgiacome** [comment]
Moment profile tests in `lgiacome/xfields/zotter_definition`
